// <auto-generated />
using System;
using Hotel.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hotel.Migrations
{
    [DbContext(typeof(HotelContext))]
    [Migration("20190804134554_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hotel.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Economy"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Ordinary"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Lux"
                        });
                });

            modelBuilder.Entity("Hotel.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("Rights");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Владелец",
                            Rights = 2047
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Администратор",
                            Rights = 488
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Посетитель",
                            Rights = 2624
                        });
                });

            modelBuilder.Entity("Hotel.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Floor");

                    b.Property<bool>("HasMiniBar");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<int>("NumberOfSeats");

                    b.Property<int>("RoomTypeId");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            Floor = "5",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "607",
                            NumberOfSeats = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 2,
                            Floor = "7",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "199",
                            NumberOfSeats = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 3,
                            Floor = "1",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "346a",
                            NumberOfSeats = 2,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 4,
                            Floor = "7",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "498",
                            NumberOfSeats = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 5,
                            Floor = "3",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "281",
                            NumberOfSeats = 2,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 6,
                            Floor = "2",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "226",
                            NumberOfSeats = 2,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 7,
                            Floor = "5",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "987b",
                            NumberOfSeats = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 8,
                            Floor = "3",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "173",
                            NumberOfSeats = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 9,
                            Floor = "4",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "202",
                            NumberOfSeats = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 10,
                            Floor = "1",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "598",
                            NumberOfSeats = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 11,
                            Floor = "6",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "773a",
                            NumberOfSeats = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 12,
                            Floor = "5",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "702b",
                            NumberOfSeats = 2,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 13,
                            Floor = "5",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "636",
                            NumberOfSeats = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 14,
                            Floor = "2",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "132",
                            NumberOfSeats = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 15,
                            Floor = "5",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "157a",
                            NumberOfSeats = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 16,
                            Floor = "1",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "821",
                            NumberOfSeats = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 17,
                            Floor = "1",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "849a",
                            NumberOfSeats = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 18,
                            Floor = "6",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "982",
                            NumberOfSeats = 2,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 19,
                            Floor = "7",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "823",
                            NumberOfSeats = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 20,
                            Floor = "1",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "339",
                            NumberOfSeats = 2,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 21,
                            Floor = "6",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "316a",
                            NumberOfSeats = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 22,
                            Floor = "7",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "730",
                            NumberOfSeats = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 23,
                            Floor = "Подвал",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "373a",
                            NumberOfSeats = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 24,
                            Floor = "5",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "537",
                            NumberOfSeats = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 25,
                            Floor = "3",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "657",
                            NumberOfSeats = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 26,
                            Floor = "7",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "472a",
                            NumberOfSeats = 2,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 27,
                            Floor = "4",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "164b",
                            NumberOfSeats = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 28,
                            Floor = "5",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "827",
                            NumberOfSeats = 2,
                            RoomTypeId = 3
                        });
                });

            modelBuilder.Entity("Hotel.Entities.RoomCost", b =>
                {
                    b.Property<int>("RoomCostId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<int>("Cost");

                    b.Property<bool>("HasMiniBar");

                    b.Property<int>("NumberOfSeats");

                    b.HasKey("RoomCostId");

                    b.HasIndex("CategoryId");

                    b.ToTable("RoomCosts");

                    b.HasData(
                        new
                        {
                            RoomCostId = 1,
                            CategoryId = 1,
                            Cost = 2000,
                            HasMiniBar = false,
                            NumberOfSeats = 1
                        },
                        new
                        {
                            RoomCostId = 2,
                            CategoryId = 1,
                            Cost = 3000,
                            HasMiniBar = false,
                            NumberOfSeats = 2
                        },
                        new
                        {
                            RoomCostId = 3,
                            CategoryId = 1,
                            Cost = 3700,
                            HasMiniBar = false,
                            NumberOfSeats = 3
                        },
                        new
                        {
                            RoomCostId = 4,
                            CategoryId = 1,
                            Cost = 4200,
                            HasMiniBar = false,
                            NumberOfSeats = 4
                        },
                        new
                        {
                            RoomCostId = 5,
                            CategoryId = 1,
                            Cost = 3000,
                            HasMiniBar = true,
                            NumberOfSeats = 1
                        },
                        new
                        {
                            RoomCostId = 6,
                            CategoryId = 1,
                            Cost = 4000,
                            HasMiniBar = true,
                            NumberOfSeats = 2
                        },
                        new
                        {
                            RoomCostId = 7,
                            CategoryId = 1,
                            Cost = 5700,
                            HasMiniBar = true,
                            NumberOfSeats = 3
                        },
                        new
                        {
                            RoomCostId = 8,
                            CategoryId = 1,
                            Cost = 6200,
                            HasMiniBar = true,
                            NumberOfSeats = 4
                        },
                        new
                        {
                            RoomCostId = 9,
                            CategoryId = 2,
                            Cost = 3000,
                            HasMiniBar = false,
                            NumberOfSeats = 1
                        },
                        new
                        {
                            RoomCostId = 10,
                            CategoryId = 2,
                            Cost = 4000,
                            HasMiniBar = false,
                            NumberOfSeats = 2
                        },
                        new
                        {
                            RoomCostId = 11,
                            CategoryId = 2,
                            Cost = 5700,
                            HasMiniBar = false,
                            NumberOfSeats = 3
                        },
                        new
                        {
                            RoomCostId = 12,
                            CategoryId = 2,
                            Cost = 6200,
                            HasMiniBar = false,
                            NumberOfSeats = 4
                        },
                        new
                        {
                            RoomCostId = 13,
                            CategoryId = 2,
                            Cost = 4500,
                            HasMiniBar = true,
                            NumberOfSeats = 1
                        },
                        new
                        {
                            RoomCostId = 14,
                            CategoryId = 2,
                            Cost = 5500,
                            HasMiniBar = true,
                            NumberOfSeats = 2
                        },
                        new
                        {
                            RoomCostId = 15,
                            CategoryId = 2,
                            Cost = 6300,
                            HasMiniBar = true,
                            NumberOfSeats = 3
                        },
                        new
                        {
                            RoomCostId = 16,
                            CategoryId = 2,
                            Cost = 6800,
                            HasMiniBar = true,
                            NumberOfSeats = 4
                        },
                        new
                        {
                            RoomCostId = 17,
                            CategoryId = 3,
                            Cost = 5000,
                            HasMiniBar = false,
                            NumberOfSeats = 1
                        },
                        new
                        {
                            RoomCostId = 18,
                            CategoryId = 3,
                            Cost = 6000,
                            HasMiniBar = false,
                            NumberOfSeats = 2
                        },
                        new
                        {
                            RoomCostId = 19,
                            CategoryId = 3,
                            Cost = 7700,
                            HasMiniBar = false,
                            NumberOfSeats = 3
                        },
                        new
                        {
                            RoomCostId = 20,
                            CategoryId = 3,
                            Cost = 8200,
                            HasMiniBar = false,
                            NumberOfSeats = 4
                        },
                        new
                        {
                            RoomCostId = 21,
                            CategoryId = 3,
                            Cost = 6800,
                            HasMiniBar = true,
                            NumberOfSeats = 1
                        },
                        new
                        {
                            RoomCostId = 22,
                            CategoryId = 3,
                            Cost = 7200,
                            HasMiniBar = true,
                            NumberOfSeats = 2
                        },
                        new
                        {
                            RoomCostId = 23,
                            CategoryId = 3,
                            Cost = 8300,
                            HasMiniBar = true,
                            NumberOfSeats = 3
                        },
                        new
                        {
                            RoomCostId = 24,
                            CategoryId = 3,
                            Cost = 10000,
                            HasMiniBar = true,
                            NumberOfSeats = 4
                        });
                });

            modelBuilder.Entity("Hotel.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CheckInTime");

                    b.Property<DateTime>("CheckOutTime");

                    b.Property<int>("Cost");

                    b.Property<bool>("IsCanceled");

                    b.Property<bool>("IsPaid");

                    b.Property<int>("RoomId");

                    b.Property<int>("UserId");

                    b.Property<bool>("isEvicted");

                    b.HasKey("TransactionId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            CheckInTime = new DateTime(2019, 7, 25, 16, 45, 54, 174, DateTimeKind.Local).AddTicks(5096),
                            CheckOutTime = new DateTime(2019, 8, 5, 16, 45, 54, 174, DateTimeKind.Local).AddTicks(5096),
                            Cost = 7200,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 12,
                            UserId = 9,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 2,
                            CheckInTime = new DateTime(2019, 8, 9, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(495),
                            CheckOutTime = new DateTime(2019, 8, 12, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(495),
                            Cost = 7200,
                            IsCanceled = false,
                            IsPaid = true,
                            RoomId = 18,
                            UserId = 15,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 3,
                            CheckInTime = new DateTime(2019, 8, 6, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(4345),
                            CheckOutTime = new DateTime(2019, 8, 8, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(4345),
                            Cost = 5500,
                            IsCanceled = false,
                            IsPaid = true,
                            RoomId = 19,
                            UserId = 6,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 4,
                            CheckInTime = new DateTime(2019, 7, 25, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(4587),
                            CheckOutTime = new DateTime(2019, 7, 31, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(4587),
                            Cost = 4000,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 14,
                            UserId = 1,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 5,
                            CheckInTime = new DateTime(2019, 8, 8, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6151),
                            CheckOutTime = new DateTime(2019, 8, 18, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6151),
                            Cost = 3000,
                            IsCanceled = false,
                            IsPaid = true,
                            RoomId = 22,
                            UserId = 17,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 6,
                            CheckInTime = new DateTime(2019, 8, 11, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6182),
                            CheckOutTime = new DateTime(2019, 8, 20, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6182),
                            Cost = 5500,
                            IsCanceled = false,
                            IsPaid = true,
                            RoomId = 25,
                            UserId = 6,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 7,
                            CheckInTime = new DateTime(2019, 7, 25, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6227),
                            CheckOutTime = new DateTime(2019, 7, 27, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6227),
                            Cost = 4000,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 13,
                            UserId = 2,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 8,
                            CheckInTime = new DateTime(2019, 8, 2, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6250),
                            CheckOutTime = new DateTime(2019, 8, 8, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6250),
                            Cost = 6000,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 6,
                            UserId = 17,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 9,
                            CheckInTime = new DateTime(2019, 8, 12, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6308),
                            CheckOutTime = new DateTime(2019, 8, 27, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6308),
                            Cost = 6000,
                            IsCanceled = false,
                            IsPaid = true,
                            RoomId = 26,
                            UserId = 15,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 10,
                            CheckInTime = new DateTime(2019, 7, 28, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6340),
                            CheckOutTime = new DateTime(2019, 7, 30, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6340),
                            Cost = 4000,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 21,
                            UserId = 13,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 11,
                            CheckInTime = new DateTime(2019, 8, 14, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6441),
                            CheckOutTime = new DateTime(2019, 8, 26, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6441),
                            Cost = 5500,
                            IsCanceled = false,
                            IsPaid = true,
                            RoomId = 24,
                            UserId = 10,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 12,
                            CheckInTime = new DateTime(2019, 8, 8, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6472),
                            CheckOutTime = new DateTime(2019, 8, 9, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6472),
                            Cost = 5500,
                            IsCanceled = false,
                            IsPaid = true,
                            RoomId = 16,
                            UserId = 17,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 13,
                            CheckInTime = new DateTime(2019, 7, 28, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6501),
                            CheckOutTime = new DateTime(2019, 8, 2, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6501),
                            Cost = 4000,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 27,
                            UserId = 4,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 14,
                            CheckInTime = new DateTime(2019, 8, 12, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6530),
                            CheckOutTime = new DateTime(2019, 8, 19, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6530),
                            Cost = 4000,
                            IsCanceled = false,
                            IsPaid = true,
                            RoomId = 17,
                            UserId = 8,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 15,
                            CheckInTime = new DateTime(2019, 8, 2, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6557),
                            CheckOutTime = new DateTime(2019, 8, 11, 16, 45, 54, 182, DateTimeKind.Local).AddTicks(6557),
                            Cost = 3000,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 10,
                            UserId = 3,
                            isEvicted = false
                        });
                });

            modelBuilder.Entity("Hotel.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("ClientId")
                        .HasMaxLength(12);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Phone");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            BirthDate = new DateTime(2014, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "226119533390",
                            Email = "Егор@mail.ru",
                            FirstName = "Егор",
                            IsDeleted = false,
                            LastName = "Астахов",
                            Phone = "7-5897-7074-8",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            BirthDate = new DateTime(2019, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "736043575691",
                            Email = "Юлия@mail.ru",
                            FirstName = "Юлия",
                            IsDeleted = false,
                            LastName = "Горбенко",
                            Phone = "5-5148-6909-7",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            BirthDate = new DateTime(2005, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "283522163358",
                            Email = "Алексей@mail.ru",
                            FirstName = "Алексей",
                            IsDeleted = false,
                            LastName = "Астахов",
                            Phone = "9-3937-7989-2",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            BirthDate = new DateTime(1995, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "306198468252",
                            Email = "Егор@mail.ru",
                            FirstName = "Егор",
                            IsDeleted = false,
                            LastName = "Ускова",
                            Phone = "3-3020-4140-9",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 5,
                            BirthDate = new DateTime(2005, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "485980336925",
                            Email = "Никита@mail.ru",
                            FirstName = "Никита",
                            IsDeleted = false,
                            LastName = "Иванов",
                            Phone = "7-4938-0013-3",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 6,
                            BirthDate = new DateTime(2007, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "911192927508",
                            Email = "Михаил@mail.ru",
                            FirstName = "Михаил",
                            IsDeleted = false,
                            LastName = "Иванов",
                            Phone = "0-2354-1178-2",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 7,
                            BirthDate = new DateTime(2000, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "775822177981",
                            Email = "Екатерина@mail.ru",
                            FirstName = "Екатерина",
                            IsDeleted = false,
                            LastName = "Воробьев",
                            Phone = "2-9542-2968-7",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 8,
                            BirthDate = new DateTime(2012, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "162609533153",
                            Email = "Никита@mail.ru",
                            FirstName = "Никита",
                            IsDeleted = false,
                            LastName = "Комаров",
                            Phone = "3-3774-2533-2",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 9,
                            BirthDate = new DateTime(2003, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "928352315168",
                            Email = "Алексей@mail.ru",
                            FirstName = "Алексей",
                            IsDeleted = false,
                            LastName = "Сидоров",
                            Phone = "8-1913-0886-9",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 10,
                            BirthDate = new DateTime(2019, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "052023867167",
                            Email = "Илья@mail.ru",
                            FirstName = "Илья",
                            IsDeleted = false,
                            LastName = "Астахов",
                            Phone = "3-7752-9924-6",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 11,
                            BirthDate = new DateTime(2016, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "302499036571",
                            Email = "Илья@mail.ru",
                            FirstName = "Илья",
                            IsDeleted = false,
                            LastName = "Астахов",
                            Phone = "1-1737-9021-0",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 12,
                            BirthDate = new DateTime(2015, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "718770209925",
                            Email = "Никита@mail.ru",
                            FirstName = "Никита",
                            IsDeleted = false,
                            LastName = "Иванов",
                            Phone = "7-2353-5696-0",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 13,
                            BirthDate = new DateTime(1997, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "666846064181",
                            Email = "Никита@mail.ru",
                            FirstName = "Никита",
                            IsDeleted = false,
                            LastName = "Астахов",
                            Phone = "5-3421-0044-9",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 14,
                            BirthDate = new DateTime(2007, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "227507737035",
                            Email = "Юлия@mail.ru",
                            FirstName = "Юлия",
                            IsDeleted = false,
                            LastName = "Горбенко",
                            Phone = "4-0245-2164-7",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 15,
                            BirthDate = new DateTime(2001, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "979965020133",
                            Email = "Егор@mail.ru",
                            FirstName = "Егор",
                            IsDeleted = false,
                            LastName = "Смирнов",
                            Phone = "2-8652-4647-6",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 16,
                            BirthDate = new DateTime(2005, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "340236898097",
                            Email = "Никита@mail.ru",
                            FirstName = "Никита",
                            IsDeleted = false,
                            LastName = "Сидоров",
                            Phone = "1-7991-9761-2",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 17,
                            BirthDate = new DateTime(2005, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "675572176210",
                            Email = "Михаил@mail.ru",
                            FirstName = "Михаил",
                            IsDeleted = false,
                            LastName = "Ситников",
                            Phone = "2-3239-9721-1",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 18,
                            BirthDate = new DateTime(2007, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "553236190792",
                            Email = "Илья@mail.ru",
                            FirstName = "Илья",
                            IsDeleted = false,
                            LastName = "Комаров",
                            Phone = "5-3244-3375-9",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 19,
                            BirthDate = new DateTime(2015, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "548672906167",
                            Email = "Алексей@mail.ru",
                            FirstName = "Алексей",
                            IsDeleted = false,
                            LastName = "Воробьев",
                            Phone = "8-9782-2358-3",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Hotel.Entities.Room", b =>
                {
                    b.HasOne("Hotel.Entities.Category", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hotel.Entities.RoomCost", b =>
                {
                    b.HasOne("Hotel.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hotel.Entities.Transaction", b =>
                {
                    b.HasOne("Hotel.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hotel.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hotel.Entities.User", b =>
                {
                    b.HasOne("Hotel.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
