// <auto-generated />
using System;
using Hotel.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hotel.Migrations
{
    [DbContext(typeof(HotelContext))]
    [Migration("20190804164155_Update_1")]
    partial class Update_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hotel.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Economy"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Ordinary"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Lux"
                        });
                });

            modelBuilder.Entity("Hotel.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("Rights");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Владелец",
                            Rights = 2047
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Администратор",
                            Rights = 488
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Посетитель",
                            Rights = 2624
                        });
                });

            modelBuilder.Entity("Hotel.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Floor");

                    b.Property<bool>("HasMiniBar");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<int>("NumberOfSeats");

                    b.Property<int>("RoomTypeId");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            Floor = "3",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "490",
                            NumberOfSeats = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 2,
                            Floor = "1",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "852",
                            NumberOfSeats = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 3,
                            Floor = "5",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "518b",
                            NumberOfSeats = 2,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 4,
                            Floor = "6",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "633",
                            NumberOfSeats = 2,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 5,
                            Floor = "4",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "320",
                            NumberOfSeats = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 6,
                            Floor = "4",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "553b",
                            NumberOfSeats = 2,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 7,
                            Floor = "Подвал",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "760",
                            NumberOfSeats = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 8,
                            Floor = "4",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "742",
                            NumberOfSeats = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 9,
                            Floor = "4",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "578",
                            NumberOfSeats = 3,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 10,
                            Floor = "5",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "594",
                            NumberOfSeats = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 11,
                            Floor = "4",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "144b",
                            NumberOfSeats = 1,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 12,
                            Floor = "4",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "388b",
                            NumberOfSeats = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 13,
                            Floor = "4",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "658a",
                            NumberOfSeats = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 14,
                            Floor = "Подвал",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "111",
                            NumberOfSeats = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 15,
                            Floor = "3",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "215",
                            NumberOfSeats = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 16,
                            Floor = "3",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "682",
                            NumberOfSeats = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 17,
                            Floor = "5",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "705",
                            NumberOfSeats = 2,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 18,
                            Floor = "1",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "910b",
                            NumberOfSeats = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 19,
                            Floor = "4",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "761a",
                            NumberOfSeats = 3,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 20,
                            Floor = "2",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "947",
                            NumberOfSeats = 1,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 21,
                            Floor = "3",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "787a",
                            NumberOfSeats = 2,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 22,
                            Floor = "5",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "793",
                            NumberOfSeats = 4,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 23,
                            Floor = "7",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "406",
                            NumberOfSeats = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 24,
                            Floor = "7",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "297",
                            NumberOfSeats = 3,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 25,
                            Floor = "7",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "751",
                            NumberOfSeats = 3,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 26,
                            Floor = "3",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "459",
                            NumberOfSeats = 4,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 27,
                            Floor = "4",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "807",
                            NumberOfSeats = 1,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 28,
                            Floor = "1",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "933",
                            NumberOfSeats = 2,
                            RoomTypeId = 2
                        });
                });

            modelBuilder.Entity("Hotel.Entities.RoomCost", b =>
                {
                    b.Property<int>("RoomCostId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<int>("Cost");

                    b.Property<bool>("HasMiniBar");

                    b.Property<int>("NumberOfSeats");

                    b.HasKey("RoomCostId");

                    b.HasIndex("CategoryId");

                    b.ToTable("RoomCosts");

                    b.HasData(
                        new
                        {
                            RoomCostId = 1,
                            CategoryId = 1,
                            Cost = 2000,
                            HasMiniBar = false,
                            NumberOfSeats = 1
                        },
                        new
                        {
                            RoomCostId = 2,
                            CategoryId = 1,
                            Cost = 3000,
                            HasMiniBar = false,
                            NumberOfSeats = 2
                        },
                        new
                        {
                            RoomCostId = 3,
                            CategoryId = 1,
                            Cost = 3700,
                            HasMiniBar = false,
                            NumberOfSeats = 3
                        },
                        new
                        {
                            RoomCostId = 4,
                            CategoryId = 1,
                            Cost = 4200,
                            HasMiniBar = false,
                            NumberOfSeats = 4
                        },
                        new
                        {
                            RoomCostId = 5,
                            CategoryId = 1,
                            Cost = 3000,
                            HasMiniBar = true,
                            NumberOfSeats = 1
                        },
                        new
                        {
                            RoomCostId = 6,
                            CategoryId = 1,
                            Cost = 4000,
                            HasMiniBar = true,
                            NumberOfSeats = 2
                        },
                        new
                        {
                            RoomCostId = 7,
                            CategoryId = 1,
                            Cost = 5700,
                            HasMiniBar = true,
                            NumberOfSeats = 3
                        },
                        new
                        {
                            RoomCostId = 8,
                            CategoryId = 1,
                            Cost = 6200,
                            HasMiniBar = true,
                            NumberOfSeats = 4
                        },
                        new
                        {
                            RoomCostId = 9,
                            CategoryId = 2,
                            Cost = 3000,
                            HasMiniBar = false,
                            NumberOfSeats = 1
                        },
                        new
                        {
                            RoomCostId = 10,
                            CategoryId = 2,
                            Cost = 4000,
                            HasMiniBar = false,
                            NumberOfSeats = 2
                        },
                        new
                        {
                            RoomCostId = 11,
                            CategoryId = 2,
                            Cost = 5700,
                            HasMiniBar = false,
                            NumberOfSeats = 3
                        },
                        new
                        {
                            RoomCostId = 12,
                            CategoryId = 2,
                            Cost = 6200,
                            HasMiniBar = false,
                            NumberOfSeats = 4
                        },
                        new
                        {
                            RoomCostId = 13,
                            CategoryId = 2,
                            Cost = 4500,
                            HasMiniBar = true,
                            NumberOfSeats = 1
                        },
                        new
                        {
                            RoomCostId = 14,
                            CategoryId = 2,
                            Cost = 5500,
                            HasMiniBar = true,
                            NumberOfSeats = 2
                        },
                        new
                        {
                            RoomCostId = 15,
                            CategoryId = 2,
                            Cost = 6300,
                            HasMiniBar = true,
                            NumberOfSeats = 3
                        },
                        new
                        {
                            RoomCostId = 16,
                            CategoryId = 2,
                            Cost = 6800,
                            HasMiniBar = true,
                            NumberOfSeats = 4
                        },
                        new
                        {
                            RoomCostId = 17,
                            CategoryId = 3,
                            Cost = 5000,
                            HasMiniBar = false,
                            NumberOfSeats = 1
                        },
                        new
                        {
                            RoomCostId = 18,
                            CategoryId = 3,
                            Cost = 6000,
                            HasMiniBar = false,
                            NumberOfSeats = 2
                        },
                        new
                        {
                            RoomCostId = 19,
                            CategoryId = 3,
                            Cost = 7700,
                            HasMiniBar = false,
                            NumberOfSeats = 3
                        },
                        new
                        {
                            RoomCostId = 20,
                            CategoryId = 3,
                            Cost = 8200,
                            HasMiniBar = false,
                            NumberOfSeats = 4
                        },
                        new
                        {
                            RoomCostId = 21,
                            CategoryId = 3,
                            Cost = 6800,
                            HasMiniBar = true,
                            NumberOfSeats = 1
                        },
                        new
                        {
                            RoomCostId = 22,
                            CategoryId = 3,
                            Cost = 7200,
                            HasMiniBar = true,
                            NumberOfSeats = 2
                        },
                        new
                        {
                            RoomCostId = 23,
                            CategoryId = 3,
                            Cost = 8300,
                            HasMiniBar = true,
                            NumberOfSeats = 3
                        },
                        new
                        {
                            RoomCostId = 24,
                            CategoryId = 3,
                            Cost = 10000,
                            HasMiniBar = true,
                            NumberOfSeats = 4
                        });
                });

            modelBuilder.Entity("Hotel.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CheckInTime");

                    b.Property<DateTime>("CheckOutTime");

                    b.Property<int>("Cost");

                    b.Property<bool>("IsCanceled");

                    b.Property<bool>("IsPaid");

                    b.Property<int>("RoomId");

                    b.Property<int>("UserId");

                    b.Property<bool>("isEvicted");

                    b.HasKey("TransactionId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            CheckInTime = new DateTime(2019, 7, 30, 19, 41, 54, 214, DateTimeKind.Local).AddTicks(8233),
                            CheckOutTime = new DateTime(2019, 8, 11, 19, 41, 54, 214, DateTimeKind.Local).AddTicks(8233),
                            Cost = 8300,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 24,
                            UserId = 4,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 2,
                            CheckInTime = new DateTime(2019, 8, 6, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(1667),
                            CheckOutTime = new DateTime(2019, 8, 7, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(1667),
                            Cost = 5000,
                            IsCanceled = false,
                            IsPaid = true,
                            RoomId = 20,
                            UserId = 7,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 3,
                            CheckInTime = new DateTime(2019, 7, 25, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(8417),
                            CheckOutTime = new DateTime(2019, 8, 1, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(8417),
                            Cost = 6000,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 17,
                            UserId = 15,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 4,
                            CheckInTime = new DateTime(2019, 8, 9, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(8634),
                            CheckOutTime = new DateTime(2019, 8, 24, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(8634),
                            Cost = 6800,
                            IsCanceled = false,
                            IsPaid = true,
                            RoomId = 11,
                            UserId = 2,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 5,
                            CheckInTime = new DateTime(2019, 7, 31, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(8691),
                            CheckOutTime = new DateTime(2019, 8, 6, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(8691),
                            Cost = 10000,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 22,
                            UserId = 8,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 6,
                            CheckInTime = new DateTime(2019, 8, 1, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(8748),
                            CheckOutTime = new DateTime(2019, 8, 2, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(8748),
                            Cost = 4000,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 28,
                            UserId = 10,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 7,
                            CheckInTime = new DateTime(2019, 8, 6, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(8788),
                            CheckOutTime = new DateTime(2019, 8, 10, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(8788),
                            Cost = 5500,
                            IsCanceled = false,
                            IsPaid = true,
                            RoomId = 2,
                            UserId = 19,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 8,
                            CheckInTime = new DateTime(2019, 8, 6, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(8970),
                            CheckOutTime = new DateTime(2019, 8, 19, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(8970),
                            Cost = 5500,
                            IsCanceled = false,
                            IsPaid = true,
                            RoomId = 15,
                            UserId = 12,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 9,
                            CheckInTime = new DateTime(2019, 8, 2, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(9016),
                            CheckOutTime = new DateTime(2019, 8, 12, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(9016),
                            Cost = 4500,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 27,
                            UserId = 14,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 10,
                            CheckInTime = new DateTime(2019, 8, 14, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(9062),
                            CheckOutTime = new DateTime(2019, 8, 23, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(9062),
                            Cost = 5700,
                            IsCanceled = false,
                            IsPaid = true,
                            RoomId = 13,
                            UserId = 16,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 11,
                            CheckInTime = new DateTime(2019, 7, 27, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(9096),
                            CheckOutTime = new DateTime(2019, 8, 1, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(9096),
                            Cost = 5500,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 2,
                            UserId = 12,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 12,
                            CheckInTime = new DateTime(2019, 8, 14, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(9136),
                            CheckOutTime = new DateTime(2019, 8, 26, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(9136),
                            Cost = 2000,
                            IsCanceled = false,
                            IsPaid = true,
                            RoomId = 16,
                            UserId = 6,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 13,
                            CheckInTime = new DateTime(2019, 7, 26, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(9170),
                            CheckOutTime = new DateTime(2019, 8, 5, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(9170),
                            Cost = 2000,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 16,
                            UserId = 12,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 14,
                            CheckInTime = new DateTime(2019, 8, 14, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(9210),
                            CheckOutTime = new DateTime(2019, 8, 18, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(9210),
                            Cost = 7200,
                            IsCanceled = false,
                            IsPaid = true,
                            RoomId = 6,
                            UserId = 5,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 15,
                            CheckInTime = new DateTime(2019, 7, 30, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(9364),
                            CheckOutTime = new DateTime(2019, 8, 5, 19, 41, 54, 228, DateTimeKind.Local).AddTicks(9364),
                            Cost = 4200,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 8,
                            UserId = 1,
                            isEvicted = false
                        });
                });

            modelBuilder.Entity("Hotel.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("ClientId")
                        .HasMaxLength(12);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Phone");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            BirthDate = new DateTime(1997, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "947422130074",
                            Email = "Екатерина@mail.ru",
                            FirstName = "Екатерина",
                            IsDeleted = false,
                            LastName = "Поляков",
                            Phone = "8-6127-3235-4",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            BirthDate = new DateTime(2010, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "643216450346",
                            Email = "Юлия@mail.ru",
                            FirstName = "Юлия",
                            IsDeleted = false,
                            LastName = "Поляков",
                            Phone = "1-8474-6412-5",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            BirthDate = new DateTime(1998, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "585085248587",
                            Email = "Ксения@mail.ru",
                            FirstName = "Ксения",
                            IsDeleted = false,
                            LastName = "Ситников",
                            Phone = "6-7623-3996-6",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            BirthDate = new DateTime(2004, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "879926475578",
                            Email = "Илья@mail.ru",
                            FirstName = "Илья",
                            IsDeleted = false,
                            LastName = "Горбенко",
                            Phone = "2-9691-5825-7",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 5,
                            BirthDate = new DateTime(2013, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "430406693983",
                            Email = "Михаил@mail.ru",
                            FirstName = "Михаил",
                            IsDeleted = false,
                            LastName = "Ситников",
                            Phone = "1-1053-9678-0",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 6,
                            BirthDate = new DateTime(2016, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "376272908834",
                            Email = "Михаил@mail.ru",
                            FirstName = "Михаил",
                            IsDeleted = false,
                            LastName = "Комаров",
                            Phone = "3-9535-3541-9",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 7,
                            BirthDate = new DateTime(2016, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "913268994689",
                            Email = "Алексей@mail.ru",
                            FirstName = "Алексей",
                            IsDeleted = false,
                            LastName = "Смирнов",
                            Phone = "1-8029-8747-9",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 8,
                            BirthDate = new DateTime(2011, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "541116392716",
                            Email = "Екатерина@mail.ru",
                            FirstName = "Екатерина",
                            IsDeleted = false,
                            LastName = "Смирнов",
                            Phone = "8-2685-9694-4",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 9,
                            BirthDate = new DateTime(2018, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "505103188138",
                            Email = "Анастасия@mail.ru",
                            FirstName = "Анастасия",
                            IsDeleted = false,
                            LastName = "Ситников",
                            Phone = "3-5880-1145-1",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 10,
                            BirthDate = new DateTime(1996, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "481423950557",
                            Email = "Екатерина@mail.ru",
                            FirstName = "Екатерина",
                            IsDeleted = false,
                            LastName = "Иванов",
                            Phone = "5-0475-2448-2",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 11,
                            BirthDate = new DateTime(2005, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "167091679659",
                            Email = "Анастасия@mail.ru",
                            FirstName = "Анастасия",
                            IsDeleted = false,
                            LastName = "Ситников",
                            Phone = "9-7095-5747-4",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 12,
                            BirthDate = new DateTime(2015, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "444376330172",
                            Email = "Михаил@mail.ru",
                            FirstName = "Михаил",
                            IsDeleted = false,
                            LastName = "Смирнов",
                            Phone = "4-2785-7233-5",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 13,
                            BirthDate = new DateTime(2005, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "206278334461",
                            Email = "Роман@mail.ru",
                            FirstName = "Роман",
                            IsDeleted = false,
                            LastName = "Воробьев",
                            Phone = "9-0948-9341-1",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 14,
                            BirthDate = new DateTime(1995, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "738461021557",
                            Email = "Михаил@mail.ru",
                            FirstName = "Михаил",
                            IsDeleted = false,
                            LastName = "Ситников",
                            Phone = "2-6341-1764-5",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 15,
                            BirthDate = new DateTime(2001, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "390095416955",
                            Email = "Никита@mail.ru",
                            FirstName = "Никита",
                            IsDeleted = false,
                            LastName = "Поляков",
                            Phone = "3-8167-7674-6",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 16,
                            BirthDate = new DateTime(2002, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "259681638220",
                            Email = "Ксения@mail.ru",
                            FirstName = "Ксения",
                            IsDeleted = false,
                            LastName = "Ускова",
                            Phone = "6-8264-4511-7",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 17,
                            BirthDate = new DateTime(2019, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "830028883794",
                            Email = "Егор@mail.ru",
                            FirstName = "Егор",
                            IsDeleted = false,
                            LastName = "Ситников",
                            Phone = "1-5437-8933-0",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 18,
                            BirthDate = new DateTime(2016, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "807493266975",
                            Email = "Михаил@mail.ru",
                            FirstName = "Михаил",
                            IsDeleted = false,
                            LastName = "Ускова",
                            Phone = "8-1050-6616-2",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 19,
                            BirthDate = new DateTime(2004, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "687232237370",
                            Email = "Алексей@mail.ru",
                            FirstName = "Алексей",
                            IsDeleted = false,
                            LastName = "Комаров",
                            Phone = "4-1940-7054-8",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Hotel.Entities.Room", b =>
                {
                    b.HasOne("Hotel.Entities.Category", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hotel.Entities.RoomCost", b =>
                {
                    b.HasOne("Hotel.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hotel.Entities.Transaction", b =>
                {
                    b.HasOne("Hotel.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hotel.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hotel.Entities.User", b =>
                {
                    b.HasOne("Hotel.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
