// <auto-generated />
using System;
using Hotel.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hotel.Migrations
{
    [DbContext(typeof(HotelContext))]
    partial class HotelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hotel.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Economy"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Ordinary"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Lux"
                        });
                });

            modelBuilder.Entity("Hotel.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("Rights");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Владелец",
                            Rights = 2047
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Администратор",
                            Rights = 488
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Посетитель",
                            Rights = 2624
                        });
                });

            modelBuilder.Entity("Hotel.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Floor");

                    b.Property<bool>("HasMiniBar");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<int>("NumberOfSeats");

                    b.Property<int>("RoomTypeId");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            Floor = "2",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "480",
                            NumberOfSeats = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 2,
                            Floor = "2",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "976",
                            NumberOfSeats = 3,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 3,
                            Floor = "6",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "650a",
                            NumberOfSeats = 4,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 4,
                            Floor = "6",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "883",
                            NumberOfSeats = 3,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 5,
                            Floor = "2",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "837",
                            NumberOfSeats = 2,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 6,
                            Floor = "1",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "853",
                            NumberOfSeats = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 7,
                            Floor = "5",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "193a",
                            NumberOfSeats = 4,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 8,
                            Floor = "6",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "387",
                            NumberOfSeats = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 9,
                            Floor = "4",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "677b",
                            NumberOfSeats = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 10,
                            Floor = "4",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "990",
                            NumberOfSeats = 3,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 11,
                            Floor = "1",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "570",
                            NumberOfSeats = 1,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 12,
                            Floor = "6",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "188b",
                            NumberOfSeats = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 13,
                            Floor = "Подвал",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "751a",
                            NumberOfSeats = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 14,
                            Floor = "Подвал",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "878",
                            NumberOfSeats = 3,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 15,
                            Floor = "1",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "665",
                            NumberOfSeats = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 16,
                            Floor = "2",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "861",
                            NumberOfSeats = 4,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 17,
                            Floor = "3",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "207b",
                            NumberOfSeats = 3,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 18,
                            Floor = "2",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "799b",
                            NumberOfSeats = 2,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 19,
                            Floor = "2",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "834",
                            NumberOfSeats = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 20,
                            Floor = "Подвал",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "787",
                            NumberOfSeats = 3,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 21,
                            Floor = "7",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "154",
                            NumberOfSeats = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 22,
                            Floor = "5",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "749",
                            NumberOfSeats = 1,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 23,
                            Floor = "2",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "973",
                            NumberOfSeats = 4,
                            RoomTypeId = 1
                        },
                        new
                        {
                            RoomId = 24,
                            Floor = "6",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "335b",
                            NumberOfSeats = 1,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 25,
                            Floor = "4",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "476",
                            NumberOfSeats = 1,
                            RoomTypeId = 3
                        },
                        new
                        {
                            RoomId = 26,
                            Floor = "5",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "954",
                            NumberOfSeats = 2,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 27,
                            Floor = "4",
                            HasMiniBar = true,
                            IsDeleted = false,
                            Name = "251",
                            NumberOfSeats = 4,
                            RoomTypeId = 2
                        },
                        new
                        {
                            RoomId = 28,
                            Floor = "Подвал",
                            HasMiniBar = false,
                            IsDeleted = false,
                            Name = "482",
                            NumberOfSeats = 2,
                            RoomTypeId = 3
                        });
                });

            modelBuilder.Entity("Hotel.Entities.RoomCost", b =>
                {
                    b.Property<int>("RoomCostId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<int>("Cost");

                    b.Property<bool>("HasMiniBar");

                    b.Property<int>("NumberOfSeats");

                    b.HasKey("RoomCostId");

                    b.HasIndex("CategoryId");

                    b.ToTable("RoomCosts");

                    b.HasData(
                        new
                        {
                            RoomCostId = 1,
                            CategoryId = 1,
                            Cost = 2000,
                            HasMiniBar = false,
                            NumberOfSeats = 1
                        },
                        new
                        {
                            RoomCostId = 2,
                            CategoryId = 1,
                            Cost = 3000,
                            HasMiniBar = false,
                            NumberOfSeats = 2
                        },
                        new
                        {
                            RoomCostId = 3,
                            CategoryId = 1,
                            Cost = 3700,
                            HasMiniBar = false,
                            NumberOfSeats = 3
                        },
                        new
                        {
                            RoomCostId = 4,
                            CategoryId = 1,
                            Cost = 4200,
                            HasMiniBar = false,
                            NumberOfSeats = 4
                        },
                        new
                        {
                            RoomCostId = 5,
                            CategoryId = 1,
                            Cost = 3000,
                            HasMiniBar = true,
                            NumberOfSeats = 1
                        },
                        new
                        {
                            RoomCostId = 6,
                            CategoryId = 1,
                            Cost = 4000,
                            HasMiniBar = true,
                            NumberOfSeats = 2
                        },
                        new
                        {
                            RoomCostId = 7,
                            CategoryId = 1,
                            Cost = 5700,
                            HasMiniBar = true,
                            NumberOfSeats = 3
                        },
                        new
                        {
                            RoomCostId = 8,
                            CategoryId = 1,
                            Cost = 6200,
                            HasMiniBar = true,
                            NumberOfSeats = 4
                        },
                        new
                        {
                            RoomCostId = 9,
                            CategoryId = 2,
                            Cost = 3000,
                            HasMiniBar = false,
                            NumberOfSeats = 1
                        },
                        new
                        {
                            RoomCostId = 10,
                            CategoryId = 2,
                            Cost = 4000,
                            HasMiniBar = false,
                            NumberOfSeats = 2
                        },
                        new
                        {
                            RoomCostId = 11,
                            CategoryId = 2,
                            Cost = 5700,
                            HasMiniBar = false,
                            NumberOfSeats = 3
                        },
                        new
                        {
                            RoomCostId = 12,
                            CategoryId = 2,
                            Cost = 6200,
                            HasMiniBar = false,
                            NumberOfSeats = 4
                        },
                        new
                        {
                            RoomCostId = 13,
                            CategoryId = 2,
                            Cost = 4500,
                            HasMiniBar = true,
                            NumberOfSeats = 1
                        },
                        new
                        {
                            RoomCostId = 14,
                            CategoryId = 2,
                            Cost = 5500,
                            HasMiniBar = true,
                            NumberOfSeats = 2
                        },
                        new
                        {
                            RoomCostId = 15,
                            CategoryId = 2,
                            Cost = 6300,
                            HasMiniBar = true,
                            NumberOfSeats = 3
                        },
                        new
                        {
                            RoomCostId = 16,
                            CategoryId = 2,
                            Cost = 6800,
                            HasMiniBar = true,
                            NumberOfSeats = 4
                        },
                        new
                        {
                            RoomCostId = 17,
                            CategoryId = 3,
                            Cost = 5000,
                            HasMiniBar = false,
                            NumberOfSeats = 1
                        },
                        new
                        {
                            RoomCostId = 18,
                            CategoryId = 3,
                            Cost = 6000,
                            HasMiniBar = false,
                            NumberOfSeats = 2
                        },
                        new
                        {
                            RoomCostId = 19,
                            CategoryId = 3,
                            Cost = 7700,
                            HasMiniBar = false,
                            NumberOfSeats = 3
                        },
                        new
                        {
                            RoomCostId = 20,
                            CategoryId = 3,
                            Cost = 8200,
                            HasMiniBar = false,
                            NumberOfSeats = 4
                        },
                        new
                        {
                            RoomCostId = 21,
                            CategoryId = 3,
                            Cost = 6800,
                            HasMiniBar = true,
                            NumberOfSeats = 1
                        },
                        new
                        {
                            RoomCostId = 22,
                            CategoryId = 3,
                            Cost = 7200,
                            HasMiniBar = true,
                            NumberOfSeats = 2
                        },
                        new
                        {
                            RoomCostId = 23,
                            CategoryId = 3,
                            Cost = 8300,
                            HasMiniBar = true,
                            NumberOfSeats = 3
                        },
                        new
                        {
                            RoomCostId = 24,
                            CategoryId = 3,
                            Cost = 10000,
                            HasMiniBar = true,
                            NumberOfSeats = 4
                        });
                });

            modelBuilder.Entity("Hotel.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CheckInTime");

                    b.Property<DateTime>("CheckOutTime");

                    b.Property<int>("Cost");

                    b.Property<bool>("IsCanceled");

                    b.Property<bool>("IsPaid");

                    b.Property<int>("RoomId");

                    b.Property<int>("UserId");

                    b.Property<bool>("isEvicted");

                    b.HasKey("TransactionId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            CheckInTime = new DateTime(2019, 8, 5, 19, 45, 57, 463, DateTimeKind.Local).AddTicks(7250),
                            CheckOutTime = new DateTime(2019, 8, 20, 19, 45, 57, 463, DateTimeKind.Local).AddTicks(7250),
                            Cost = 5000,
                            IsCanceled = false,
                            IsPaid = true,
                            RoomId = 25,
                            UserId = 15,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 2,
                            CheckInTime = new DateTime(2019, 8, 1, 19, 45, 57, 480, DateTimeKind.Local).AddTicks(2312),
                            CheckOutTime = new DateTime(2019, 8, 6, 19, 45, 57, 480, DateTimeKind.Local).AddTicks(2312),
                            Cost = 7200,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 5,
                            UserId = 7,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 3,
                            CheckInTime = new DateTime(2019, 8, 14, 19, 45, 57, 480, DateTimeKind.Local).AddTicks(9690),
                            CheckOutTime = new DateTime(2019, 8, 21, 19, 45, 57, 480, DateTimeKind.Local).AddTicks(9690),
                            Cost = 4000,
                            IsCanceled = false,
                            IsPaid = true,
                            RoomId = 18,
                            UserId = 2,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 4,
                            CheckInTime = new DateTime(2019, 8, 11, 19, 45, 57, 480, DateTimeKind.Local).AddTicks(9941),
                            CheckOutTime = new DateTime(2019, 8, 25, 19, 45, 57, 480, DateTimeKind.Local).AddTicks(9941),
                            Cost = 6200,
                            IsCanceled = false,
                            IsPaid = true,
                            RoomId = 23,
                            UserId = 12,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 5,
                            CheckInTime = new DateTime(2019, 7, 29, 19, 45, 57, 480, DateTimeKind.Local).AddTicks(9992),
                            CheckOutTime = new DateTime(2019, 8, 1, 19, 45, 57, 480, DateTimeKind.Local).AddTicks(9992),
                            Cost = 5000,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 11,
                            UserId = 16,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 6,
                            CheckInTime = new DateTime(2019, 8, 4, 19, 45, 57, 481, DateTimeKind.Local).AddTicks(38),
                            CheckOutTime = new DateTime(2019, 8, 16, 19, 45, 57, 481, DateTimeKind.Local).AddTicks(38),
                            Cost = 5000,
                            IsCanceled = false,
                            IsPaid = true,
                            RoomId = 24,
                            UserId = 17,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 7,
                            CheckInTime = new DateTime(2019, 7, 28, 19, 45, 57, 481, DateTimeKind.Local).AddTicks(271),
                            CheckOutTime = new DateTime(2019, 7, 30, 19, 45, 57, 481, DateTimeKind.Local).AddTicks(271),
                            Cost = 3700,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 13,
                            UserId = 7,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 8,
                            CheckInTime = new DateTime(2019, 7, 26, 19, 45, 57, 481, DateTimeKind.Local).AddTicks(306),
                            CheckOutTime = new DateTime(2019, 8, 5, 19, 45, 57, 481, DateTimeKind.Local).AddTicks(306),
                            Cost = 3000,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 22,
                            UserId = 15,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 9,
                            CheckInTime = new DateTime(2019, 7, 27, 19, 45, 57, 481, DateTimeKind.Local).AddTicks(340),
                            CheckOutTime = new DateTime(2019, 8, 8, 19, 45, 57, 481, DateTimeKind.Local).AddTicks(340),
                            Cost = 8200,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 3,
                            UserId = 1,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 10,
                            CheckInTime = new DateTime(2019, 7, 31, 19, 45, 57, 481, DateTimeKind.Local).AddTicks(386),
                            CheckOutTime = new DateTime(2019, 8, 10, 19, 45, 57, 481, DateTimeKind.Local).AddTicks(386),
                            Cost = 3000,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 8,
                            UserId = 12,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 11,
                            CheckInTime = new DateTime(2019, 7, 31, 19, 45, 57, 481, DateTimeKind.Local).AddTicks(420),
                            CheckOutTime = new DateTime(2019, 8, 5, 19, 45, 57, 481, DateTimeKind.Local).AddTicks(420),
                            Cost = 6000,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 28,
                            UserId = 11,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 12,
                            CheckInTime = new DateTime(2019, 7, 26, 19, 45, 57, 481, DateTimeKind.Local).AddTicks(465),
                            CheckOutTime = new DateTime(2019, 7, 28, 19, 45, 57, 481, DateTimeKind.Local).AddTicks(465),
                            Cost = 4200,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 1,
                            UserId = 14,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 13,
                            CheckInTime = new DateTime(2019, 7, 27, 19, 45, 57, 481, DateTimeKind.Local).AddTicks(500),
                            CheckOutTime = new DateTime(2019, 8, 10, 19, 45, 57, 481, DateTimeKind.Local).AddTicks(500),
                            Cost = 4000,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 15,
                            UserId = 4,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 14,
                            CheckInTime = new DateTime(2019, 7, 30, 19, 45, 57, 481, DateTimeKind.Local).AddTicks(676),
                            CheckOutTime = new DateTime(2019, 8, 14, 19, 45, 57, 481, DateTimeKind.Local).AddTicks(676),
                            Cost = 3000,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 21,
                            UserId = 11,
                            isEvicted = false
                        },
                        new
                        {
                            TransactionId = 15,
                            CheckInTime = new DateTime(2019, 7, 27, 19, 45, 57, 481, DateTimeKind.Local).AddTicks(722),
                            CheckOutTime = new DateTime(2019, 8, 11, 19, 45, 57, 481, DateTimeKind.Local).AddTicks(722),
                            Cost = 6800,
                            IsCanceled = false,
                            IsPaid = false,
                            RoomId = 7,
                            UserId = 14,
                            isEvicted = false
                        });
                });

            modelBuilder.Entity("Hotel.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("ClientId")
                        .HasMaxLength(12);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Phone");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            BirthDate = new DateTime(2003, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "202912990595",
                            Email = "Егор@mail.ru",
                            FirstName = "Егор",
                            IsDeleted = false,
                            LastName = "Горбенко",
                            Password = "1234567890",
                            Phone = "2-5230-9099-5",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            BirthDate = new DateTime(1998, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "535522516768",
                            Email = "Егор@mail.ru",
                            FirstName = "Егор",
                            IsDeleted = false,
                            LastName = "Смирнов",
                            Password = "1234567890",
                            Phone = "9-1458-8310-4",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            BirthDate = new DateTime(2016, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "863179925593",
                            Email = "Никита@mail.ru",
                            FirstName = "Никита",
                            IsDeleted = false,
                            LastName = "Горбенко",
                            Password = "1234567890",
                            Phone = "0-4234-6362-0",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            BirthDate = new DateTime(2004, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "308672635362",
                            Email = "Алексей@mail.ru",
                            FirstName = "Алексей",
                            IsDeleted = false,
                            LastName = "Ускова",
                            Password = "1234567890",
                            Phone = "3-4684-1946-8",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 5,
                            BirthDate = new DateTime(2015, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "268798163381",
                            Email = "Илья@mail.ru",
                            FirstName = "Илья",
                            IsDeleted = false,
                            LastName = "Горбенко",
                            Password = "1234567890",
                            Phone = "7-6639-6039-0",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 6,
                            BirthDate = new DateTime(2003, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "420712686558",
                            Email = "Роман@mail.ru",
                            FirstName = "Роман",
                            IsDeleted = false,
                            LastName = "Астахов",
                            Password = "1234567890",
                            Phone = "2-0847-1469-7",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 7,
                            BirthDate = new DateTime(2007, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "629288080461",
                            Email = "Роман@mail.ru",
                            FirstName = "Роман",
                            IsDeleted = false,
                            LastName = "Комаров",
                            Password = "1234567890",
                            Phone = "4-5650-6090-7",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 8,
                            BirthDate = new DateTime(1995, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "671914290507",
                            Email = "Ксения@mail.ru",
                            FirstName = "Ксения",
                            IsDeleted = false,
                            LastName = "Ситников",
                            Password = "1234567890",
                            Phone = "1-2918-4429-3",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 9,
                            BirthDate = new DateTime(2012, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "307221998108",
                            Email = "Юлия@mail.ru",
                            FirstName = "Юлия",
                            IsDeleted = false,
                            LastName = "Ускова",
                            Password = "1234567890",
                            Phone = "5-9518-3655-8",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 10,
                            BirthDate = new DateTime(2018, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "580109150835",
                            Email = "Ксения@mail.ru",
                            FirstName = "Ксения",
                            IsDeleted = false,
                            LastName = "Горбенко",
                            Password = "1234567890",
                            Phone = "3-1859-3614-2",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 11,
                            BirthDate = new DateTime(2004, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "179546929729",
                            Email = "Екатерина@mail.ru",
                            FirstName = "Екатерина",
                            IsDeleted = false,
                            LastName = "Астахов",
                            Password = "1234567890",
                            Phone = "0-7766-6962-4",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 12,
                            BirthDate = new DateTime(2000, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "684865286822",
                            Email = "Анастасия@mail.ru",
                            FirstName = "Анастасия",
                            IsDeleted = false,
                            LastName = "Ускова",
                            Password = "1234567890",
                            Phone = "8-3815-8311-8",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 13,
                            BirthDate = new DateTime(1998, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "315658677874",
                            Email = "Ксения@mail.ru",
                            FirstName = "Ксения",
                            IsDeleted = false,
                            LastName = "Смирнов",
                            Password = "1234567890",
                            Phone = "3-2801-1884-7",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 14,
                            BirthDate = new DateTime(1999, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "650067000347",
                            Email = "Михаил@mail.ru",
                            FirstName = "Михаил",
                            IsDeleted = false,
                            LastName = "Поляков",
                            Password = "1234567890",
                            Phone = "0-0109-6329-2",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 15,
                            BirthDate = new DateTime(1995, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "077419854825",
                            Email = "Никита@mail.ru",
                            FirstName = "Никита",
                            IsDeleted = false,
                            LastName = "Ситников",
                            Password = "1234567890",
                            Phone = "5-4273-9758-1",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 16,
                            BirthDate = new DateTime(1998, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "215639029502",
                            Email = "Екатерина@mail.ru",
                            FirstName = "Екатерина",
                            IsDeleted = false,
                            LastName = "Воробьев",
                            Password = "1234567890",
                            Phone = "7-4497-2800-4",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 17,
                            BirthDate = new DateTime(2005, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "425182779873",
                            Email = "Юлия@mail.ru",
                            FirstName = "Юлия",
                            IsDeleted = false,
                            LastName = "Горбенко",
                            Password = "1234567890",
                            Phone = "5-2727-9715-6",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 18,
                            BirthDate = new DateTime(2018, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "017244999864",
                            Email = "Ксения@mail.ru",
                            FirstName = "Ксения",
                            IsDeleted = false,
                            LastName = "Ситников",
                            Password = "1234567890",
                            Phone = "1-3741-4755-2",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 19,
                            BirthDate = new DateTime(2004, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClientId = "606416709709",
                            Email = "Илья@mail.ru",
                            FirstName = "Илья",
                            IsDeleted = false,
                            LastName = "Ситников",
                            Password = "1234567890",
                            Phone = "3-5606-2263-5",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Hotel.Entities.Room", b =>
                {
                    b.HasOne("Hotel.Entities.Category", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hotel.Entities.RoomCost", b =>
                {
                    b.HasOne("Hotel.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hotel.Entities.Transaction", b =>
                {
                    b.HasOne("Hotel.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hotel.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hotel.Entities.User", b =>
                {
                    b.HasOne("Hotel.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
